version: 2
registries:
  k9-inntektsmelding-frontend:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-inntektsmelding-frontend
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - k9-inntektsmelding-frontend
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    groups:
      minor:
        exclude-patterns:
          - "@navikt/vite-mode"
        update-types:
          - "minor"
          - "patch"
      prod-major:
        dependency-type: "production"
        update-types:
          - "major"
      dev-major:
        dependency-type: "development"
        update-types:
          - "major"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
